name: yb-wls-demo

networks:
  ybnet:
      ipam:
        config:
          - subnet: 10.5.0.0/16
            gateway: 10.5.0.1
volumes:
  yugabyted-1:
  yugabyted-2:
  yugabyted-3:

services:
  yugabyted-1:
    image: yugabytedb/yugabyte:2.23.0.0-b710
    networks:
      ybnet:
        ipv4_address: 10.5.0.11
    cap_add:
      - NET_ADMIN
    container_name: yugabyted-1
    hostname: yugabyted-1.local
    restart: unless-stopped
    ports:
      - "7000:7000"
      - "9000:7000"
      - "15433:15433"
      - "5433:5433"
      - "9042:9042"
    volumes:
      - yugabyted-1:/home/yugabyte/yb-data
      - ./demo.master.gflags:/home/yugabyte/demo.master.gflags
      - ./demo.tserver.gflags:/home/yugabyte/demo.tserver.gflags
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        bin/yugabyted start \
          --insecure \
          --base_dir=/home/yugabyte/yb-data \
          --advertise_address=yugabyted-1.local \
          --cloud_location=local.docker.zone1 \
          --fault_tolerance=zone \
          --master_flags="flagfile=/home/yugabyte/demo.master.gflags" \
          --tserver_flags="flagfile=/home/yugabyte/demo.tserver.gflags" \
          --daemon=false
    healthcheck:
      test: ./postgres/bin/pg_isready -U yugabyte -d yugabyte -h yugabyted-1.local
      start_period: 120s
      start_interval: 1s
      interval: 10s
      timeout: 5s
      retries: 3
  yugabyted-2:
    image: yugabytedb/yugabyte:2.23.0.0-b710
    networks:
      ybnet:
        ipv4_address: 10.5.0.21
    cap_add:
      - NET_ADMIN
    container_name: yugabyted-2
    hostname: yugabyted-2.local
    restart: unless-stopped
    volumes:
      - yugabyted-2:/home/yugabyte/yb-data
      - ./demo.master.gflags:/home/yugabyte/demo.master.gflags
      - ./demo.tserver.gflags:/home/yugabyte/demo.tserver.gflags

    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        bin/yugabyted start \
          --insecure \
          --base_dir=/home/yugabyte/yb-data \
          --advertise_address=yugabyted-2.local \
          --cloud_location=local.docker.zone2 \
          --fault_tolerance=zone \
          --master_flags="flagfile=/home/yugabyte/demo.master.gflags" \
          --tserver_flags="flagfile=/home/yugabyte/demo.tserver.gflags" \
          --daemon=false \
          --ui=false \
          --join=yugabyted-1.local
    healthcheck:
      test: ./postgres/bin/pg_isready -U yugabyte -d yugabyte -h yugabyted-2.local
      start_period: 120s
      start_interval: 1s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      yugabyted-1:
        condition: service_healthy
  yugabyted-3:
    image: yugabytedb/yugabyte:2.23.0.0-b710
    networks:
      ybnet:
        ipv4_address: 10.5.0.31
    cap_add:
      - NET_ADMIN
    container_name: yugabyted-3
    hostname: yugabyted-3.local
    restart: unless-stopped
    volumes:
      - yugabyted-3:/home/yugabyte/yb-data
      - ./demo.master.gflags:/home/yugabyte/demo.master.gflags
      - ./demo.tserver.gflags:/home/yugabyte/demo.tserver.gflags
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        bin/yugabyted start \
          --insecure \
          --base_dir=/home/yugabyte/yb-data \
          --advertise_address=yugabyted-3.local \
          --cloud_location=local.docker.zone3 \
          --fault_tolerance=zone \
          --master_flags="flagfile=/home/yugabyte/demo.master.gflags" \
          --tserver_flags="flagfile=/home/yugabyte/demo.tserver.gflags" \
          --daemon=false \
          --ui=false \
          --join=yugabyted-2.local
    healthcheck:
      test: ./postgres/bin/pg_isready -U yugabyte -d yugabyte -h yugabyted-3.local
      start_period: 120s
      start_interval: 1s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      yugabyted-2:
        condition: service_healthy
  shell:
    # container_name: shell
    hostname: shell.local
    image: yugabytedb/yugabyte:2.23.0.0-b710
    command: tail -f /dev/null
    networks:
      ybnet:
  app:
    build:
      context: .
      dockerfile: demo.Dockerfile
    container_name: app
    networks:
      ybnet:
    hostname: app.local
    environment:
        SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_SERVERNAME: yugabyted-1.local
        node_c: yugabyted-1.local
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      yugabyted-1:
        condition: service_healthy
      yugabyted-2:
        condition: service_healthy
      yugabyted-3:
        condition: service_healthy
  sqlpad:
    image: sqlpad/sqlpad:6.11.2
    hostname: sqlpad.local
    container_name: sqlpad
    ports:
      - 3001:3000
    networks:
      ybnet:
    volumes:
      - ./sqlpad/seed-data:/etc/sqlpad/seed-data
    environment:
      SQLPAD_ADMIN: 'admin'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
    depends_on:
      yugabyted-1:
        condition: service_healthy
