{
 "title": "YugabyteDB Query Stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "By Client Host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT client_addr, count(client_addr) \nFROM pg_stat_activity \ngroup by client_addr\nhaving client_addr is not null"
    }
   ]
  },
  {
   "title": "By Database",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT datname, count(client_addr) \nFROM pg_stat_activity \ngroup by 1\n"
    }
   ]
  },
  {
   "title": "By User",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT usename, count(datid) \nFROM pg_stat_activity \ngroup by 1\n"
    }
   ]
  },
  {
   "title": "By App",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT application_name, count(datid) \nFROM pg_stat_activity \ngroup by 1\n"
    }
   ]
  }
 ]
}